name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar tests y generar cobertura
        run: |
          pytest --cov=src --cov-report=xml
          pip install coverage[toml]       # para el HTML
          coverage html -d htmlcov

      - name: Resumen en el job
        if: always()
        run: |
          echo "### Cobertura" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          coverage report >> $GITHUB_STEP_SUMMARY

      - name: Publicar HTML de cobertura como artefacto
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: htmlcov/**
